import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import * as dotenv from "dotenv";

dotenv.config();

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

type CustodianSeed = {
  name: string;
  legalName?: string;
  aliases?: string[];
  phone?: string;
  fax?: string;
  email?: string;
  website?: string;
  mailingAddress?: string;
  overnightAddress?: string;
  typicalProcessingDays?: number;
  minProcessingDays?: number;
  maxProcessingDays?: number;
  signatureRequirements?: string;
  medallionRequired?: boolean;
  medallionThreshold?: number;
  notarizationRequired?: boolean;
  acceptsElectronic?: boolean;
  acceptsDigitalSignature?: boolean;
  supportsACATS?: boolean;
  overview?: string;
  quirks?: string[];
  commonForms?: string[];
  tags?: string[];
};

const CUSTODIANS: CustodianSeed[] = [
  {
    name: "Fidelity Investments",
    legalName: "Fidelity Brokerage Services LLC",
    aliases: ["Fidelity", "FMR", "Fidelity NetBenefits"],
    phone: "800-343-3548",
    website: "https://www.fidelity.com",
    mailingAddress: "Fidelity Investments, PO Box 770001, Cincinnati, OH 45277-0002",
    overnightAddress: "Fidelity Investments, 100 Crosby Parkway KC1K, Covington, KY 41015",
    typicalProcessingDays: 7,
    minProcessingDays: 5,
    maxProcessingDays: 10,
    signatureRequirements: "Client wet signature required for most distribution/rollover forms. Medallion signature guarantee required on distributions over $100,000 sent to a third party or new address.",
    medallionRequired: true,
    medallionThreshold: 100000,
    acceptsElectronic: true,
    acceptsDigitalSignature: true,
    supportsACATS: true,
    overview: "Large full-service broker and recordkeeper. Accepts electronic signature (NetBenefits) for many in-plan transactions, but external rollovers typically require wet-signed paperwork.",
    quirks: [
      "NetBenefits-hosted 401(k)s frequently require the plan-specific distribution form; generic LOA not accepted",
      "Check issuance defaults to Cincinnati lockbox — always confirm overnight address when time-sensitive",
      "Will not accept ACATS for 401(k) rollovers — must be a check or wire initiated by Fidelity",
    ],
    commonForms: ["Distribution Form", "Direct Rollover Request", "One-Time Withdrawal (IRA)"],
    tags: ["broker", "recordkeeper", "IRA", "401k"],
  },
  {
    name: "Vanguard",
    legalName: "The Vanguard Group, Inc.",
    aliases: ["Vanguard Brokerage", "VBS", "VGI"],
    phone: "800-523-1188",
    website: "https://www.vanguard.com",
    mailingAddress: "Vanguard, PO Box 982901, El Paso, TX 79998-2901",
    overnightAddress: "Vanguard, 5951 Luckett Court Suite A1, El Paso, TX 79932-1882",
    typicalProcessingDays: 10,
    minProcessingDays: 7,
    maxProcessingDays: 14,
    signatureRequirements: "Wet signature required on rollover paperwork. Medallion required on withdrawals over $250,000 and for address changes within 15 days of request.",
    medallionRequired: true,
    medallionThreshold: 250000,
    acceptsElectronic: true,
    acceptsDigitalSignature: false,
    supportsACATS: true,
    overview: "Mutual-fund-first custodian; brokerage side now on their transitioned brokerage platform. Slower than average for rollover processing.",
    quirks: [
      "Ascensus-administered small-business 401(k)s route through a separate process — check whether the plan is Vanguard-direct or Ascensus-serviced",
      "Will often mail the check directly to the client even when 'FBO' is specified — always follow up",
      "Does not accept DocuSign for external rollover requests",
    ],
    commonForms: ["Distribution Request Form", "IRA Rollover Certification"],
    tags: ["mutual-fund", "broker", "IRA", "401k"],
  },
  {
    name: "Charles Schwab",
    legalName: "Charles Schwab & Co., Inc.",
    aliases: ["Schwab", "Schwab Retirement Plan Services", "SRPS"],
    phone: "800-435-4000",
    website: "https://www.schwab.com",
    mailingAddress: "Charles Schwab & Co., PO Box 628291, Orlando, FL 32862-8291",
    overnightAddress: "Charles Schwab & Co., 1958 Summit Park Drive Suite 200, Orlando, FL 32810",
    typicalProcessingDays: 5,
    minProcessingDays: 3,
    maxProcessingDays: 7,
    signatureRequirements: "Wet or Schwab-generated e-sign accepted. Medallion required on withdrawals over $100,000 to third-party accounts.",
    medallionRequired: true,
    medallionThreshold: 100000,
    acceptsElectronic: true,
    acceptsDigitalSignature: true,
    supportsACATS: true,
    overview: "Acquired TD Ameritrade — all retail TD accounts now on Schwab platform. Generally the fastest major custodian for rollovers.",
    quirks: [
      "Post-TD conversion, some account numbers changed; always verify with most recent statement",
      "Schwab Retirement Plan Services (recordkeeper arm) is a separate org from Schwab brokerage — different fax and processing timeline",
      "Accepts Schwab-generated DocuSign but not third-party e-sign providers for distributions",
    ],
    commonForms: ["IRA Distribution Request Form", "Letter of Authorization", "ACATS Transfer Form"],
    tags: ["broker", "IRA", "401k"],
  },
  {
    name: "Empower Retirement",
    legalName: "Empower Annuity Insurance Company of America",
    aliases: ["Empower", "Great-West", "Prudential Retirement", "MassMutual Retirement"],
    phone: "855-756-4738",
    website: "https://www.empower.com",
    mailingAddress: "Empower Retirement, PO Box 173764, Denver, CO 80217-3764",
    overnightAddress: "Empower Retirement, 8515 E Orchard Rd, Greenwood Village, CO 80111",
    typicalProcessingDays: 10,
    minProcessingDays: 7,
    maxProcessingDays: 14,
    signatureRequirements: "Wet signature required. Spousal consent with notarization required for married participants taking distributions from plans subject to QJSA.",
    medallionRequired: false,
    notarizationRequired: true,
    acceptsElectronic: false,
    acceptsDigitalSignature: false,
    supportsACATS: false,
    overview: "Large recordkeeper; absorbed Prudential Retirement (2022) and MassMutual's retirement business (2020). Plan-specific forms vary widely.",
    quirks: [
      "Form availability depends on plan sponsor — always pull the plan's distribution kit from the participant portal",
      "Requires spousal consent + notary on QJSA plans even for direct rollovers",
      "Does not support ACATS; distributions go out as paper checks with 7-10 day mail time after cut",
      "Legacy Prudential plan IDs still appear on some statements — must map to current Empower plan number",
    ],
    commonForms: ["Plan Distribution Request", "Spousal Consent Form", "Direct Rollover Election"],
    tags: ["recordkeeper", "401k", "403b"],
  },
  {
    name: "Principal Financial Group",
    legalName: "Principal Life Insurance Company",
    aliases: ["Principal", "Principal Retirement"],
    phone: "800-547-7754",
    website: "https://www.principal.com",
    mailingAddress: "Principal Life Insurance Company, PO Box 9394, Des Moines, IA 50306-9394",
    typicalProcessingDays: 10,
    minProcessingDays: 7,
    maxProcessingDays: 14,
    signatureRequirements: "Wet signature required. Notarized spousal consent required for QJSA plans.",
    medallionRequired: false,
    notarizationRequired: true,
    acceptsElectronic: false,
    supportsACATS: false,
    overview: "Large recordkeeper serving small-to-mid-market 401(k)s. Plan kits vary significantly — always download the specific plan's forms.",
    quirks: [
      "Plan kits are plan-specific; generic Principal distribution form is frequently rejected",
      "Requires notarized spousal consent on most QJSA plans even if spouse is the rollover recipient",
      "Checks are issued from Des Moines — add 5-7 days mail time after processing",
    ],
    commonForms: ["Distribution Request Form", "Spousal Consent"],
    tags: ["recordkeeper", "401k"],
  },
  {
    name: "TIAA",
    legalName: "Teachers Insurance and Annuity Association of America",
    aliases: ["TIAA-CREF", "CREF"],
    phone: "800-842-2252",
    website: "https://www.tiaa.org",
    mailingAddress: "TIAA, PO Box 1259, Charlotte, NC 28201-1259",
    typicalProcessingDays: 14,
    minProcessingDays: 10,
    maxProcessingDays: 21,
    signatureRequirements: "Wet signature required on most rollover paperwork. Some contracts (TIAA Traditional) have surrender/TPA restrictions that can only be met with 10-year Transfer Payout Annuity.",
    medallionRequired: false,
    acceptsElectronic: false,
    acceptsDigitalSignature: false,
    supportsACATS: false,
    overview: "Higher-education and non-profit 403(b)/457 specialist. TIAA Traditional annuity accumulations often cannot be rolled over in full without a 10-year payout election.",
    quirks: [
      "TIAA Traditional RA contracts limit lump-sum withdrawals; most require a 10-year Transfer Payout Annuity (TPA) — plan for decade-long rollover",
      "GRA (Group Retirement Annuity) and RC (Retirement Choice) contracts have different liquidity rules than GSRA/RCP — always confirm contract type",
      "403(b) loans cannot be rolled over; must be paid off or defaulted first",
      "Processes rollovers in Charlotte NC, not legacy NY address",
    ],
    commonForms: ["Transfer Payout Annuity Election", "Retirement Plan Distribution Request"],
    tags: ["403b", "457", "annuity", "university"],
  },
  {
    name: "Merrill Lynch",
    legalName: "Merrill Lynch, Pierce, Fenner & Smith Incorporated",
    aliases: ["Merrill", "Merrill Edge", "ML", "Bank of America Merrill"],
    phone: "800-637-7455",
    website: "https://www.merrilledge.com",
    mailingAddress: "Merrill, PO Box 1501, Pennington, NJ 08534-1501",
    typicalProcessingDays: 7,
    minProcessingDays: 5,
    maxProcessingDays: 10,
    signatureRequirements: "Wet signature required; Medallion needed for third-party distributions over $100,000.",
    medallionRequired: true,
    medallionThreshold: 100000,
    acceptsElectronic: true,
    supportsACATS: true,
    overview: "Bank of America's brokerage arm. Merrill Edge is the self-directed online channel; full-service Merrill Lynch uses separate forms.",
    quirks: [
      "Merrill Edge and full-service Merrill Lynch use different distribution forms — confirm which platform the account sits on",
      "Walk-in Medallion stamps available at most Bank of America branches",
      "401(k) recordkeeping business (Merrill Lynch Retirement Group) follows plan-specific process, not brokerage",
    ],
    commonForms: ["IRA Distribution Form", "401(k) Direct Rollover Request"],
    tags: ["broker", "IRA", "401k"],
  },
  {
    name: "JPMorgan Chase",
    legalName: "J.P. Morgan Securities LLC",
    aliases: ["JPMorgan", "JP Morgan", "Chase Investments", "J.P. Morgan Chase", "JPMS"],
    phone: "800-392-5749",
    website: "https://www.chase.com/personal/investments",
    typicalProcessingDays: 10,
    minProcessingDays: 7,
    maxProcessingDays: 14,
    signatureRequirements: "Wet signature required; Medallion required on transfers over $250,000.",
    medallionRequired: true,
    medallionThreshold: 250000,
    acceptsElectronic: false,
    supportsACATS: true,
    overview: "Chase branch-hosted investment accounts and J.P. Morgan Securities brokerage. Branch staff often involved in signing and mailing paperwork.",
    quirks: [
      "Chase Private Client and J.P. Morgan Self-Directed route through different service teams",
      "Branch associates will sometimes hold paperwork 'pending review' for days — call directly to confirm receipt",
      "Retirement plan business (JPMorgan Retirement Plan Services) was sold to Empower in 2014 — legacy accounts now at Empower",
    ],
    commonForms: ["IRA Distribution Request", "Retirement Account Withdrawal Form"],
    tags: ["broker", "bank", "IRA"],
  },
  {
    name: "Edward Jones",
    legalName: "Edward D. Jones & Co., L.P.",
    aliases: ["EJ", "Jones"],
    phone: "800-441-2357",
    website: "https://www.edwardjones.com",
    mailingAddress: "Edward Jones, 12555 Manchester Road, St. Louis, MO 63131",
    typicalProcessingDays: 7,
    minProcessingDays: 5,
    maxProcessingDays: 10,
    signatureRequirements: "Wet signature required; advisor involvement expected on every distribution.",
    medallionRequired: true,
    medallionThreshold: 100000,
    acceptsElectronic: false,
    supportsACATS: true,
    overview: "Branch-based broker with ~19,000 FAs. Expect the client's Edward Jones FA to be involved in every step — direct client-custodian contact is uncommon.",
    quirks: [
      "Every distribution involves the client's local FA — build time for FA review into the timeline",
      "Check is often hand-delivered from the branch, not mailed from STL",
      "ACATS-eligible but branch will frequently push back to try to retain assets — send ACATS early in case of delays",
    ],
    commonForms: ["IRA Distribution Form"],
    tags: ["broker", "branch", "IRA"],
  },
  {
    name: "Raymond James",
    legalName: "Raymond James Financial Services, Inc.",
    aliases: ["RJ", "Raymond James & Associates", "RJFS"],
    phone: "800-248-8863",
    website: "https://www.raymondjames.com",
    typicalProcessingDays: 7,
    minProcessingDays: 5,
    maxProcessingDays: 10,
    signatureRequirements: "Wet signature required; Medallion required on non-ACATS distributions over $100,000.",
    medallionRequired: true,
    medallionThreshold: 100000,
    acceptsElectronic: false,
    supportsACATS: true,
    overview: "Mid-size broker-dealer; branch-based. Check for both RJ&A (employee channel) and RJFS (independent channel) — both run through Raymond James home office in St. Petersburg, FL.",
    quirks: [
      "RJ&A and RJFS use the same forms but route through different branch-ops teams",
      "ACATS generally clears quickly (5-7 days) but advisor pushback is common",
    ],
    commonForms: ["IRA Distribution Request", "ACATS Transfer Form"],
    tags: ["broker", "branch", "IRA"],
  },
  {
    name: "LPL Financial",
    legalName: "LPL Financial LLC",
    aliases: ["LPL"],
    phone: "800-558-7567",
    website: "https://www.lpl.com",
    typicalProcessingDays: 7,
    minProcessingDays: 5,
    maxProcessingDays: 10,
    signatureRequirements: "Wet or DocuSign (LPL-generated) accepted. Medallion required on third-party distributions over $100,000.",
    medallionRequired: true,
    medallionThreshold: 100000,
    acceptsElectronic: true,
    acceptsDigitalSignature: true,
    supportsACATS: true,
    overview: "Largest independent B/D in the US. Clearing through LPL's own platform. Accepts LPL-generated DocuSign for most forms.",
    quirks: [
      "Advisor-initiated DocuSign packages clear fastest; client-initiated requests require printed wet signature",
      "Check-issuance turnaround is reliably 3-5 business days once paperwork is in good order",
    ],
    commonForms: ["IRA Distribution Form", "ACATS Transfer"],
    tags: ["broker", "independent", "IRA"],
  },
  {
    name: "Ameriprise Financial",
    legalName: "Ameriprise Financial Services, LLC",
    aliases: ["Ameriprise"],
    phone: "800-862-7919",
    website: "https://www.ameriprise.com",
    typicalProcessingDays: 10,
    minProcessingDays: 7,
    maxProcessingDays: 14,
    signatureRequirements: "Wet signature required; Medallion required on transfers over $100,000.",
    medallionRequired: true,
    medallionThreshold: 100000,
    acceptsElectronic: false,
    supportsACATS: true,
    overview: "Full-service broker. Advisor-centric process; branch involvement in every outbound transfer.",
    quirks: [
      "Branch retention process — expect at least one outreach from the client's Ameriprise FA before ACATS clears",
      "Variable annuities on the Ameriprise platform require separate surrender paperwork and may have CDSC",
    ],
    commonForms: ["IRA Distribution", "ACATS Transfer"],
    tags: ["broker", "IRA"],
  },
  {
    name: "E*TRADE",
    legalName: "E*TRADE Securities LLC",
    aliases: ["ETRADE", "E-Trade", "E*TRADE from Morgan Stanley", "Morgan Stanley at Work"],
    phone: "800-387-2331",
    website: "https://us.etrade.com",
    typicalProcessingDays: 5,
    minProcessingDays: 3,
    maxProcessingDays: 7,
    signatureRequirements: "Wet signature required on most forms; Medallion required on distributions over $100,000 to non-linked accounts.",
    medallionRequired: true,
    medallionThreshold: 100000,
    acceptsElectronic: true,
    supportsACATS: true,
    overview: "Acquired by Morgan Stanley (2020). Retail E*TRADE accounts still on the E*TRADE platform as of 2024; employer stock plan accounts moving to Morgan Stanley at Work.",
    quirks: [
      "Stock plan (ESPP/RSU) accounts route through Morgan Stanley at Work, separate from retail E*TRADE",
      "Fast ACATS processing — typically 3-5 days",
    ],
    commonForms: ["IRA Distribution Request"],
    tags: ["broker", "IRA"],
  },
  {
    name: "Morgan Stanley",
    legalName: "Morgan Stanley Smith Barney LLC",
    aliases: ["MS", "Morgan Stanley Wealth Management", "MSSB", "Smith Barney"],
    phone: "888-454-3965",
    website: "https://www.morganstanley.com",
    typicalProcessingDays: 10,
    minProcessingDays: 7,
    maxProcessingDays: 14,
    signatureRequirements: "Wet signature required; Medallion required on most third-party outbound transfers regardless of amount.",
    medallionRequired: true,
    medallionThreshold: 0,
    acceptsElectronic: false,
    supportsACATS: true,
    overview: "Full-service wirehouse. Stricter Medallion posture than most — default assumption is that Medallion is required.",
    quirks: [
      "Medallion signature guarantee required on virtually all third-party outbound transfers — no dollar threshold",
      "Branch FA retention calls are standard; expect delays if client is high-net-worth",
      "Morgan Stanley at Work (employer equity) is a separate subsidiary with different ops",
    ],
    commonForms: ["IRA Distribution Form", "ACATS Transfer Form"],
    tags: ["broker", "wirehouse", "IRA"],
  },
  {
    name: "UBS Financial Services",
    legalName: "UBS Financial Services Inc.",
    aliases: ["UBS"],
    phone: "888-279-3343",
    website: "https://www.ubs.com/us",
    typicalProcessingDays: 10,
    minProcessingDays: 7,
    maxProcessingDays: 14,
    signatureRequirements: "Wet signature required; Medallion required on third-party outbound transfers.",
    medallionRequired: true,
    medallionThreshold: 0,
    acceptsElectronic: false,
    supportsACATS: true,
    overview: "Wirehouse serving HNW and UHNW clients. Advisor-heavy process.",
    quirks: [
      "Medallion required on nearly all outbound transfers regardless of size",
      "FA retention outreach is standard protocol",
    ],
    commonForms: ["IRA Distribution Form"],
    tags: ["broker", "wirehouse", "IRA"],
  },
  {
    name: "Wells Fargo Advisors",
    legalName: "Wells Fargo Clearing Services, LLC",
    aliases: ["WFA", "Wells Fargo", "WF Advisors"],
    phone: "800-872-3377",
    website: "https://www.wellsfargoadvisors.com",
    typicalProcessingDays: 10,
    minProcessingDays: 7,
    maxProcessingDays: 14,
    signatureRequirements: "Wet signature required; Medallion required on third-party distributions over $100,000.",
    medallionRequired: true,
    medallionThreshold: 100000,
    acceptsElectronic: false,
    supportsACATS: true,
    overview: "Full-service broker. Branch-centric workflow.",
    quirks: [
      "Walk-in Medallion stamps available at Wells Fargo bank branches for existing customers",
      "Branch FA review required on outbound transfers",
    ],
    commonForms: ["IRA Distribution Form", "ACATS Transfer"],
    tags: ["broker", "bank", "IRA"],
  },
  {
    name: "Voya Financial",
    legalName: "Voya Retirement Insurance and Annuity Company",
    aliases: ["Voya", "ING Retirement", "ING U.S."],
    phone: "800-584-6001",
    website: "https://www.voya.com",
    typicalProcessingDays: 10,
    minProcessingDays: 7,
    maxProcessingDays: 14,
    signatureRequirements: "Wet signature required; notarized spousal consent required for QJSA plans.",
    medallionRequired: false,
    notarizationRequired: true,
    acceptsElectronic: false,
    supportsACATS: false,
    overview: "Recordkeeper; formerly ING U.S. Rebranded 2014. Strong presence in 403(b)/457 for public sector.",
    quirks: [
      "Public-sector 457 plans often have employer-approval step before Voya will process — build in 5-10 extra days",
      "Plan-specific distribution kit required; generic form rejected",
    ],
    commonForms: ["Distribution Request", "Spousal Consent"],
    tags: ["recordkeeper", "403b", "457"],
  },
  {
    name: "John Hancock Retirement",
    legalName: "John Hancock Retirement Plan Services LLC",
    aliases: ["John Hancock", "JH Retirement", "JH"],
    phone: "800-294-3575",
    website: "https://www.johnhancock.com/retirement",
    typicalProcessingDays: 10,
    minProcessingDays: 7,
    maxProcessingDays: 14,
    signatureRequirements: "Wet signature required; notarized spousal consent on QJSA plans.",
    notarizationRequired: true,
    acceptsElectronic: false,
    supportsACATS: false,
    overview: "Mid-market 401(k) recordkeeper. Plan kits are plan-specific.",
    quirks: [
      "Plan-specific forms only — always pull from plan portal",
      "Check issuance 5-7 days post-processing",
    ],
    commonForms: ["Plan Distribution Request"],
    tags: ["recordkeeper", "401k"],
  },
  {
    name: "Transamerica",
    legalName: "Transamerica Retirement Solutions, LLC",
    aliases: ["Transamerica", "TRS"],
    phone: "800-755-5801",
    website: "https://www.transamerica.com",
    typicalProcessingDays: 10,
    minProcessingDays: 7,
    maxProcessingDays: 14,
    signatureRequirements: "Wet signature required; notarized spousal consent on QJSA plans.",
    notarizationRequired: true,
    acceptsElectronic: false,
    supportsACATS: false,
    overview: "Mid-market recordkeeper.",
    quirks: [
      "Distribution kits available via participant portal — not via customer service by default",
      "Slower than average on in-service withdrawal processing",
    ],
    commonForms: ["Distribution Request"],
    tags: ["recordkeeper", "401k", "403b"],
  },
  {
    name: "ADP Retirement Services",
    legalName: "ADP, Inc.",
    aliases: ["ADP", "ADP 401(k)"],
    phone: "800-695-7526",
    website: "https://www.adp.com/what-we-offer/products/adp-retirement-services.aspx",
    typicalProcessingDays: 7,
    minProcessingDays: 5,
    maxProcessingDays: 10,
    signatureRequirements: "Wet signature required; notarized spousal consent on QJSA plans.",
    notarizationRequired: true,
    acceptsElectronic: true,
    supportsACATS: false,
    overview: "Payroll-integrated 401(k) recordkeeper. Small-to-mid market.",
    quirks: [
      "Employer payroll approval step required — participant-only requests get held",
      "Online distribution request available for terminated employees via mykplan portal",
    ],
    commonForms: ["Distribution Request"],
    tags: ["recordkeeper", "401k", "small-business"],
  },
  {
    name: "Paychex",
    legalName: "Paychex, Inc.",
    aliases: ["Paychex Retirement Services"],
    phone: "877-244-1771",
    website: "https://www.paychex.com/retirement-services",
    typicalProcessingDays: 7,
    minProcessingDays: 5,
    maxProcessingDays: 10,
    signatureRequirements: "Wet signature required.",
    notarizationRequired: true,
    acceptsElectronic: false,
    supportsACATS: false,
    overview: "Small-business payroll provider; 401(k) recordkeeping for small plans.",
    quirks: [
      "Employer approval required on every distribution",
      "Forms vary by plan — pull from plan administrator portal",
    ],
    commonForms: ["Distribution Request"],
    tags: ["recordkeeper", "401k", "small-business"],
  },
  {
    name: "Ascensus",
    legalName: "Ascensus, LLC",
    aliases: ["Ascensus Retirement"],
    phone: "800-345-6363",
    website: "https://www.ascensus.com",
    typicalProcessingDays: 10,
    minProcessingDays: 7,
    maxProcessingDays: 14,
    signatureRequirements: "Wet signature required.",
    acceptsElectronic: false,
    supportsACATS: false,
    overview: "Recordkeeper for small-business 401(k)s including Vanguard-branded and many SIMPLE/SEP IRA programs.",
    quirks: [
      "Backend for many 'other brand' retirement plans — the client may not know Ascensus is involved",
      "SIMPLE IRAs have 2-year rule: 25% penalty on non-SIMPLE rollovers before 2-year anniversary",
    ],
    commonForms: ["Distribution Request", "SIMPLE IRA Rollover"],
    tags: ["recordkeeper", "small-business", "SIMPLE", "SEP"],
  },
  {
    name: "American Funds",
    legalName: "Capital Research and Management Company",
    aliases: ["American Funds", "Capital Group", "CRMC"],
    phone: "800-421-4225",
    website: "https://www.americanfunds.com",
    typicalProcessingDays: 7,
    minProcessingDays: 5,
    maxProcessingDays: 10,
    signatureRequirements: "Wet signature required; Medallion required on transfers over $250,000 or address changes within 30 days.",
    medallionRequired: true,
    medallionThreshold: 250000,
    acceptsElectronic: false,
    supportsACATS: true,
    overview: "Mutual fund family; direct-at-fund accounts in addition to brokerage-held positions. Direct accounts have separate process from brokerage-held.",
    quirks: [
      "Direct-at-fund accounts cannot use ACATS — must liquidate and wire",
      "Class A shares have CDSC consideration if redeemed within load period",
    ],
    commonForms: ["IRA Distribution Form", "Fund Liquidation"],
    tags: ["mutual-fund", "IRA"],
  },
  {
    name: "T. Rowe Price",
    legalName: "T. Rowe Price Services, Inc.",
    aliases: ["TRP", "T Rowe", "T. Rowe"],
    phone: "800-225-5132",
    website: "https://www.troweprice.com",
    typicalProcessingDays: 7,
    minProcessingDays: 5,
    maxProcessingDays: 10,
    signatureRequirements: "Wet signature required; Medallion required on transfers over $250,000.",
    medallionRequired: true,
    medallionThreshold: 250000,
    acceptsElectronic: true,
    supportsACATS: true,
    overview: "Mutual fund family + recordkeeper. Fast processing for direct retail IRAs.",
    quirks: [
      "Direct-at-fund IRAs process quickly; recordkept 401(k)s are slower and plan-specific",
      "Accepts T. Rowe-generated DocuSign for most retail IRA transactions",
    ],
    commonForms: ["IRA Distribution Form", "Direct Rollover"],
    tags: ["mutual-fund", "recordkeeper", "IRA", "401k"],
  },
  {
    name: "Nationwide Retirement Solutions",
    legalName: "Nationwide Retirement Solutions, Inc.",
    aliases: ["Nationwide", "NRS"],
    phone: "877-677-3678",
    website: "https://www.nationwide.com/personal/investing/retirement-plans",
    typicalProcessingDays: 10,
    minProcessingDays: 7,
    maxProcessingDays: 14,
    signatureRequirements: "Wet signature required; notarized spousal consent on QJSA plans.",
    notarizationRequired: true,
    acceptsElectronic: false,
    supportsACATS: false,
    overview: "Recordkeeper specializing in public sector 457(b) and 401(a) plans.",
    quirks: [
      "Public-sector 457 plans require employer approval before distribution",
      "Plan-specific kit required",
    ],
    commonForms: ["Distribution Request"],
    tags: ["recordkeeper", "457", "401a", "public-sector"],
  },
  {
    name: "Securian Financial",
    legalName: "Securian Financial Group, Inc.",
    aliases: ["Securian", "Minnesota Life"],
    phone: "800-362-3141",
    website: "https://www.securian.com",
    typicalProcessingDays: 10,
    minProcessingDays: 7,
    maxProcessingDays: 14,
    signatureRequirements: "Wet signature required.",
    acceptsElectronic: false,
    supportsACATS: false,
    overview: "Insurance-based recordkeeper; annuity-centric plans.",
    quirks: [
      "Most contracts are fixed/variable annuities — surrender charges and MVA may apply",
      "Not a retail-direct brand; always expect employer-sponsored plan context",
    ],
    commonForms: ["Distribution Request", "Annuity Surrender"],
    tags: ["recordkeeper", "annuity"],
  },
];

async function main() {
  console.log(`Seeding ${CUSTODIANS.length} custodians...`);

  for (const c of CUSTODIANS) {
    await prisma.custodian.upsert({
      where: { name: c.name },
      update: {
        ...c,
        aliases: c.aliases ?? [],
        quirks: c.quirks ?? [],
        commonForms: c.commonForms ?? [],
        tags: c.tags ?? [],
        lastVerifiedAt: new Date(),
      },
      create: {
        ...c,
        aliases: c.aliases ?? [],
        quirks: c.quirks ?? [],
        commonForms: c.commonForms ?? [],
        tags: c.tags ?? [],
        lastVerifiedAt: new Date(),
      },
    });
    console.log(`  ✓ ${c.name}`);
  }

  console.log("Done.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
